while True:
    n = int(input())
    while n - 1000 >= 0:
        print('M',end = '')
        n-=1000
    if n - 900 >= 0:
        print('CM',end='')
        n-=900
    if n - 500 >= 0:
        print('D',end='')
        n -= 500
    if n - 400 >= 0:
        print('CD',end='')
        n-=400
    while n -100 >= 0:
        print("C",end='')
        n-=100
    if n -90 >= 0:
        print("XC",end='')
        n-=90
    if n-50 >= 0:
        print("L",end='')
        n-=50
    if n-40 >= 0:
        print("XL",end='')
        n-=40
    while n-10 >=0:
        print("X",end='')
        n-=10
    if n-9>=0:
        print("IX",end='')
        n-=9
    if n-5>=0:
        print("V",end='')
        n-=5
    if n-4>=0:
        print("IV",end='')
        n-=4
    while(n-1>=0):
        print("I",end='')
        n-=1
    print()